# Generated by Django 3.0.6 on 2020-05-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='')),
                ('Address', models.TextField()),
                ('Contact', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Fees', models.PositiveIntegerField()),
                ('DID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
                ('Fees', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='')),
                ('Age', models.PositiveIntegerField()),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('Address', models.TextField()),
                ('Contact', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('DOJ', models.DateField()),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Bed')),
                ('DID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Description', models.TextField()),
                ('Fees', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('LID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Laboratory')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Total', models.PositiveIntegerField()),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='RID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
    ]
