# Generated by Django 3.0.6 on 2020-05-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200529_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='pics')),
                ('DOB', models.DateField()),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('Address', models.TextField()),
                ('Contact', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
