# Generated by Django 3.0.6 on 2020-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200530_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
